all:
  children:
    webservers:
      hosts:
        web-staging-01:
          ansible_host: 192.168.2.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/staging_key
      vars:
        environment: staging
        nginx_worker_processes: 2
        nginx_worker_connections: 512
        ssl_enabled: false
    
    monitoring:
      hosts:
        monitor-staging-01:
          ansible_host: 192.168.2.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/staging_key
      vars:
        environment: staging
        prometheus_retention_days: 7
        grafana_admin_password: "{{ vault_grafana_admin_password }}" 