all:
  children:
    webservers:
      hosts:
        web-prod-01:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
        web-prod-02:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
      vars:
        environment: production
        nginx_worker_processes: 4
        nginx_worker_connections: 1024
        ssl_enabled: true
    
    monitoring:
      hosts:
        monitor-prod-01:
          ansible_host: 192.168.1.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
      vars:
        environment: production
        prometheus_retention_days: 30
        grafana_admin_password: "{{ vault_grafana_admin_password }}"
    
    loadbalancers:
      hosts:
        lb-prod-01:
          ansible_host: 192.168.1.30
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/prod_key
      vars:
        environment: production
        haproxy_stats_port: 8404 